server:
  port: 0
spring:
  application:
    name: auth-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpwd
    url: jdbc:mysql://localhost:1111/espresso_club_auth?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  secret: 576D5A7134743777217A25432646294A404E635266556A586E3272357538782F