server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.handler.predicate: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.support: DEBUG
    org.springframework.cloud.gateway.web: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  main:
    web-application-type: servlet
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
