server:
  port: 8080
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  main:
    web-application-type: servlet
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
